name: "My Python Action"
description: "A project-specific composite action"
inputs:
  python-version:
    description: "Python version to use"
    required: true
  command:
    description: command to execute"
    required: true
  dependencies:
    description: "Python dependencies to install"
    required: false

runs:
  using: "composite"
  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ inputs.dependencies }}
        if ( Test-Path test_requirements.txt ){ pip install -r test_requirements.txt }
      shell: pwsh

    - name: Run command
      run: |
        echo "Running command: ${{ inputs.command }}"
        Invoke-Expression "${{ inputs.command }}"
      shell: pwsh
