name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    uses: ./.github/workflows/python-reusable.yml
    with:
      dependencies: ". ruff"
      command: |
        # run basic ruff check with isort in black profile
        ruff check --output-format github --extend-select I .
        # use ruff format to check black 
        ruff format .

  test:
      uses: ./.github/workflows/python-reusable.yml        
      with:
        dependencies: ". pytest"
        command: |
          $Env:PY_VER = "${{ matrix.python-version }}"
          pytest --junit-xml "test_results$PY_VER.xml"
        upload_files: test_results${{ matrix.python-version }}.xml
  
  display_results:
    runs-on: windows-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Download Test Result
        uses: actions/download-artifact@v4
        with:
          name: test_results${{ matrix.python-version }}.xml
      - uses: test-summary/action@v2
        with:
          paths: test_results${{ matrix.python-version }}.xml
