name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    uses: ./.github/workflows/python-reusable.yml
    with:
      dependencies: ". ruff"
      command: |
        # run basic ruff check with isort in black profile
        ruff check --output-format github --extend-select I .
        # use ruff format to check black 
        ruff format .

  test:
      uses: ./.github/workflows/python-reusable.yml
      with:
        dependencies: ". pytest"
        command: |
          pytest --junit-xml test_results.xml
        upload_files: test_results.xml
  
  display_results:
    runs-on: windows-latest
    steps:
      - name: Download Test Result
        uses: actions/download-artifact@v3
        with:
          name: test_results.xml
      - uses: test-summary/action@v2
        with:
          paths: test_results.xml
